server:
  port: 8888

spring:
  application:
    name: demo-message-ipc-web

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

--- #################### 日志文件配置 ####################
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径

--- #################### 系统相关配置 ####################
demo-mipc:

